// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Yami_SkipTitle","status":true,"description":"Skip the title scene for testing purpose.","parameters":{}},
{"name":"YED_WordWrap","status":true,"description":"v1.0.0 This plugin provides word wrap feature, so that a long text will be properly broken down into lines.","parameters":{}},
{"name":"kill_counter_(mv)","status":true,"description":"Allows you to track number of enemies killed","parameters":{}}
];
